-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 19:49:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ex3
-- -----------------------------------------------------
USE `ex3` ;

-- -----------------------------------------------------
-- Table `ex3`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`User` ;

CREATE TABLE IF NOT EXISTS `ex3`.`User` (
  `User_Id` INT NOT NULL,
  `User_Name` VARCHAR(30) NULL,
  `Pwd` VARCHAR(30) NULL COMMENT 'Must contain capital, small letters and numbers',
  `Sex` ENUM('0', '1') NULL COMMENT '1 for male and 0 for female',
  `Address` VARCHAR(100) NULL,
  `Membership` ENUM('1', '0') DEFAULT '0',
  PRIMARY KEY (`User_Id`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex3`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`Goods` ;

CREATE TABLE IF NOT EXISTS `ex3`.`Goods` (
  `Goods_Id` INT NOT NULL,
  `Goods_Name` VARCHAR(30) NULL,
  `Goods_Price` REAL NULL COMMENT 'non-negative real number',
  `Goods_Stock` INT NULL COMMENT 'non-negative integer',
  PRIMARY KEY (`Goods_Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex3`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`Cart` ;

CREATE TABLE IF NOT EXISTS `ex3`.`Cart` (
  `Cart_Id` INT auto_increment,
  `User_Id` INT NULL,
  `Cart_Cost` REAL NULL COMMENT 'Cart_Amount should be a non-negative real number',
  PRIMARY KEY (`Cart_Id`),
  INDEX `User_Id_idx` (`User_Id` ASC),
  CONSTRAINT `Cart_User_Id`
    FOREIGN KEY (`User_Id`)
    REFERENCES `ex3`.`User` (`User_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex3`.`Bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`Bill` ;

CREATE TABLE IF NOT EXISTS `ex3`.`Bill` (
  `Bill_Id` INT auto_increment,
  `Cart_Id` INT NULL,
  `User_Id` INT NULL,
  `Bill_No` TEXT(16) NULL COMMENT '16-digit-long string',
  `Bill_Amount` REAL COMMENT 'non-negative real number',
  `Bill_Time` DATETIME NULL,
  PRIMARY KEY (`Bill_Id`),
  INDEX `User_Id_idx` (`User_Id` ASC),
  INDEX `Cart_Id_idx` (`Cart_Id` ASC),
  CONSTRAINT `Bill_User_Id`
    FOREIGN KEY (`User_Id`)
    REFERENCES `ex3`.`User` (`User_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Bill_Cart_Id`
    FOREIGN KEY (`Cart_Id`)
    REFERENCES `ex3`.`Cart` (`Cart_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex3`.`Bill_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`Bill_Info` ;

CREATE TABLE IF NOT EXISTS `ex3`.`Bill_Info` (
  `Bill_Info_Id` INT auto_increment,
  `Bill_Id` INT NULL,
  `Goods_Id` INT NULL,
  `Goods_Num` INT NULL COMMENT 'non-negative integer',
  `Goods_Price` REAL NULL COMMENT 'non-negative real number',
  PRIMARY KEY (`Bill_Info_Id`),
  INDEX `Goods_Id_idx` (`Goods_Id` ASC),
  INDEX `Bill_Id_idx` (`Bill_Id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ex3`.`Cart_Info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`Cart_Info` ;

CREATE TABLE IF NOT EXISTS `ex3`.`Cart_Info` (
  `Cart_Info_Id` INT auto_increment,
  `Cart_Id` INT NULL,
  `Goods_Id` INT NULL,
  `Goods_Num` INT NULL COMMENT 'Goods_Num should be a non-negative integer',
  `Add_Time` DATETIME NULL,
  `Goods_Price` REAL NULL COMMENT 'Goods_Price should be a non-negative real number',
  PRIMARY KEY (`Cart_Info_Id`),
  INDEX `Cart_Id_idx` (`Cart_Id` ASC),
  INDEX `Goods_Id_idx` (`Goods_Id` ASC),
  CONSTRAINT `Cart_Info_Cart_Id`
    FOREIGN KEY (`Cart_Id`)
    REFERENCES `ex3`.`Cart` (`Cart_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cart_Info_Goods_Id`
    FOREIGN KEY (`Goods_Id`)
    REFERENCES `ex3`.`Goods` (`Goods_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ex3`.`Refund` (
  `Refund_Id` INT NOT NULL AUTO_INCREMENT,
  `Bill_Id` INT NULL,
  `Goods_Id` INT NULL,
  `Goods_Num` INT NULL,
  `Goods_Price` REAL NULL,
  `Refund_Time` DATETIME,
  PRIMARY KEY (`Refund_Id`),
  INDEX `Bill_Id_idx` (`Goods_Id` ASC),
  CONSTRAINT `Bill_Id`
    FOREIGN KEY (`Goods_Id`)
    REFERENCES `ex3`.`Goods` (`Goods_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ex3`.`Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ex3`.`Feedback` ;

CREATE TABLE IF NOT EXISTS `ex3`.`Feedback` (
  `Feedback_Id` INT NOT NULL AUTO_INCREMENT,
  `Comment` VARCHAR(300) NULL,
  `Bill_Id` INT NULL,
  `User_Id` INT NULL,
  PRIMARY KEY (`Feedback_Id`),
  INDEX `Bill_Id_idx` (`Bill_Id` ASC),
  CONSTRAINT `Bill_Id_feedback`
    FOREIGN KEY (`Bill_Id`)
    REFERENCES `ex3`.`Bill` (`Bill_Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;