-- MySQL Script generated by MySQL Workbench
-- Sat Oct  5 10:18:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema EX1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EX1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EX1` DEFAULT CHARACTER SET utf8 ;
USE `EX1` ;

-- -----------------------------------------------------
-- Table `EX1`.`Provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Provider`;
CREATE TABLE IF NOT EXISTS `EX1`.`Provider` (
  `provider_account` VARCHAR(16) NOT NULL,
  `provider_name` VARCHAR(45) NULL,
  `provider_password` VARCHAR(16) NULL,
  `provider_age` INT NULL,
  `provider_gender` ENUM('male', 'female') NULL,
  `provider_phone` CHAR(8) NULL,
  PRIMARY KEY (`provider_account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Client`;
CREATE TABLE IF NOT EXISTS `EX1`.`Client` (
  `client_account` VARCHAR(16) NOT NULL,
  `client_password` VARCHAR(16) NULL,
  `client_name` VARCHAR(45) NULL,
  `client_age` INT NULL,
  `client_gender` ENUM('male', 'female') NULL,
  `client_phone` CHAR(8) NULL,
  `client_address` VARCHAR(45) NULL,
  `client_rank` ENUM('top', 'senior', 'normal', 'non') NULL,
  `client_score` INT NULL,
  `client_discount` FLOAT NULL,
  PRIMARY KEY (`client_account`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Deal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Deal`;
CREATE TABLE IF NOT EXISTS `EX1`.`Deal` (
  `id_deal` INT NOT NULL,
  `deal_price` INT NULL,
  `deal_status` ENUM('Not processed', 'Sent', 'Completed', 'Refunded') NOT NULL,
  `deal_refund_reason` VARCHAR(200) NULL,
  `deal_score` INT NULL,
  `deal_num` INT NULL,
  `deal_start_time` DATETIME NULL,
  `deal_sent_time` DATETIME NULL,
  PRIMARY KEY (`id_deal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Goods`;
CREATE TABLE IF NOT EXISTS `EX1`.`Goods` (
  `id_goods` INT NOT NULL,
  `goods_name` VARCHAR(45) NULL,
  `goods_num` INT NULL,
  `goods_discount` FLOAT NULL,
  `goods_price` INT NULL,
  `goods_prod_date` DATETIME NULL,
  `goods_exp_date` DATETIME NULL,
  `Deal_id_deal` INT NOT NULL,
  PRIMARY KEY (`id_goods`, `Deal_id_deal`),
  INDEX `fk_Goods_Deal1_idx` (`Deal_id_deal` ASC),
  CONSTRAINT `fk_Goods_Deal1`
    FOREIGN KEY (`Deal_id_deal`)
    REFERENCES `EX1`.`Deal` (`id_deal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Provider_has_Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Provider_has_Goods`;
CREATE TABLE IF NOT EXISTS `EX1`.`Provider_has_Goods` (
  `Provider_provider_account` VARCHAR(16) NOT NULL,
  `Goods_id_goods` INT NOT NULL,
  PRIMARY KEY (`Provider_provider_account`, `Goods_id_goods`),
  INDEX `fk_Provider_has_Goods_Goods1_idx` (`Goods_id_goods` ASC),
  INDEX `fk_Provider_has_Goods_Provider_idx` (`Provider_provider_account` ASC),
  CONSTRAINT `fk_Provider_has_Goods_Provider`
    FOREIGN KEY (`Provider_provider_account`)
    REFERENCES `EX1`.`Provider` (`provider_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Provider_has_Goods_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `EX1`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Goods_Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Goods_Type`;
CREATE TABLE IF NOT EXISTS `EX1`.`Goods_Type` (
  `goods_type` ENUM('clothing', 'entertainment', 'food') NOT NULL,
  PRIMARY KEY (`goods_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Goods_Type_has_Goods`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Goods_Type_has_Goods`;
CREATE TABLE IF NOT EXISTS `EX1`.`Goods_Type_has_Goods` (
  `Goods_Type_goods_type` ENUM('clothing', 'entertainment', 'food') NOT NULL,
  `Goods_id_goods` INT NOT NULL,
  PRIMARY KEY (`Goods_Type_goods_type`, `Goods_id_goods`),
  INDEX `fk_Goods_Type_has_Goods_Goods1_idx` (`Goods_id_goods` ASC),
  INDEX `fk_Goods_Type_has_Goods_Goods_Type1_idx` (`Goods_Type_goods_type` ASC),
  CONSTRAINT `fk_Goods_Type_has_Goods_Goods_Type1`
    FOREIGN KEY (`Goods_Type_goods_type`)
    REFERENCES `EX1`.`Goods_Type` (`goods_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Goods_Type_has_Goods_Goods1`
    FOREIGN KEY (`Goods_id_goods`)
    REFERENCES `EX1`.`Goods` (`id_goods`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EX1`.`Feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EX1`.`Feedback`;
CREATE TABLE IF NOT EXISTS `EX1`.`Feedback` (
  `id_feedback` INT NOT NULL,
  `feedback_content` VARCHAR(200) NULL,
  `feedback_score` FLOAT NULL,
  `feedback_time` DATETIME NULL,
  `Client_client_account` VARCHAR(16) NOT NULL,
  `Deal_id_deal` INT NOT NULL,
  PRIMARY KEY (`id_feedback`, `Client_client_account`, `Deal_id_deal`),
  INDEX `fk_Feedback_Client1_idx` (`Client_client_account` ASC),
  INDEX `fk_Feedback_Deal1_idx` (`Deal_id_deal` ASC),
  CONSTRAINT `fk_Feedback_Client1`
    FOREIGN KEY (`Client_client_account`)
    REFERENCES `EX1`.`Client` (`client_account`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Deal1`
    FOREIGN KEY (`Deal_id_deal`)
    REFERENCES `EX1`.`Deal` (`id_deal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET SQL_SAFE_UPDATES = 0;
